{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nova-scanner.fullname" . }}
  labels:
    {{- include "nova-scanner.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.github.token }}
  GITHUB_TOKEN: {{ .Values.github.token | quote }}
  {{- end }}
  {{- if .Values.github.owner }}
  GITHUB_OWNER: {{ .Values.github.owner | quote }}
  {{- end }}
  {{- if .Values.github.repo }}
  GITHUB_REPO: {{ .Values.github.repo | quote }}
  {{- end }}
{{- end }}
