apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nova-scanner

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - externalsecret.yaml
  - cronjob.yaml

labels:
  - pairs:
      app.kubernetes.io/name: nova-scanner
      app.kubernetes.io/part-of: nova-scanner
    includeSelectors: false

commonAnnotations:
  app.kubernetes.io/managed-by: kustomize
